version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./app-1
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./app:/var/www/html/
        ports:
            - 8000:80
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: mysql@123
          MYSQL_DATABASE: myhmsdb
          MYSQL_USER: kirik
          MYSQL_PASSWORD: kirik@123
        ports:
          - "9906:3306"
        volumes:
          - ./sql/myhmsdb.sql:/docker-entrypoint-initdb.d/backup.sql
        #command: bash -c "sleep 10 && mysql -u root -p myhsmdb < /docker-entrypoint-initdb.d/backup.sql"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db