version: "3"
services:
  app:
    image: myapp
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: myhsmdb
    command: ["--skip-innodb", "--default-authentication-plugin=mysql_native_password"]
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:81"
    environment:
      PMA_HOST: db
